#############################################################################
# Makefile for building: kd_tree
# Generated by qmake (3.1) (Qt 6.3.2)
# Project:  kd_tree.pro
# Template: app
# Command: /usr/local/bin/qmake -o Makefile kd_tree.pro
#############################################################################

MAKEFILE      = Makefile

EQ            = =

####### Compiler, tools and options

CC            = /Library/Developer/CommandLineTools/usr/bin/clang
CXX           = /Library/Developer/CommandLineTools/usr/bin/clang++
DEFINES       = 
CFLAGS        = -pipe -O2 $(EXPORT_ARCH_ARGS) -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk -mmacosx-version-min=10.15 -Wall -Wextra -fPIC $(DEFINES)
CXXFLAGS      = -pipe -stdlib=libc++ -std=c++11 -Wreturn-type -O2 -std=gnu++1z $(EXPORT_ARCH_ARGS) -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk -mmacosx-version-min=10.15 -Wall -Wextra -fPIC $(DEFINES)
INCPATH       = -I. -I/usr/local/share/qt/mkspecs/macx-clang
QMAKE         = /usr/local/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
QINSTALL      = /usr/local/bin/qmake -install qinstall
QINSTALL_PROGRAM = /usr/local/bin/qmake -install qinstall -exe
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = kd_tree.0.0
DISTDIR = /Users/Viktor/programming/kd_tree/.tmp/kd_tree.0.0
LINK          = /Library/Developer/CommandLineTools/usr/bin/clang++
LFLAGS        = -stdlib=libc++ -headerpad_max_install_names $(EXPORT_ARCH_ARGS) -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk -mmacosx-version-min=10.15 -Wl,-rpath,@executable_path/../Frameworks
LIBS          = $(SUBLIBS)    
AR            = /Library/Developer/CommandLineTools/usr/bin/ar cq
RANLIB        = /Library/Developer/CommandLineTools/usr/bin/ranlib -s
SED           = sed
STRIP         = strip

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = kd_tree.cpp \
		test-harness.cpp 
OBJECTS       = kd_tree.o \
		test-harness.o
DIST          = .qmake.stash \
		kd_tree.pro /Users/Viktor/programming/kd_tree/BoundedPQueue.h \
		/Users/Viktor/programming/kd_tree/kd_tree.h \
		/Users/Viktor/programming/kd_tree/Point.h kd_tree.cpp \
		test-harness.cpp
QMAKE_TARGET  = kd_tree
DESTDIR       = 
TARGET        = kd_tree

####### Custom Variables
EXPORT_QMAKE_MAC_SDK = macosx
EXPORT_QMAKE_MAC_SDK_VERSION = 11.1
EXPORT_QMAKE_XCODE_DEVELOPER_PATH = /Library/Developer/CommandLineTools
EXPORT__QMAKE_STASH_ = /Users/Viktor/programming/kd_tree/.qmake.stash
EXPORT_VALID_ARCHS = x86_64
EXPORT_DEFAULT_ARCHS = x86_64
EXPORT_ARCHS = $(filter $(EXPORT_VALID_ARCHS), $(if $(ARCHS), $(ARCHS), $(if $(EXPORT_DEFAULT_ARCHS), $(EXPORT_DEFAULT_ARCHS), $(EXPORT_VALID_ARCHS))))
EXPORT_ARCH_ARGS = $(foreach arch, $(if $(EXPORT_ARCHS), $(EXPORT_ARCHS), $(EXPORT_VALID_ARCHS)), -arch $(arch))
EXPORT__PRO_FILE_ = /Users/Viktor/programming/kd_tree/kd_tree.pro


include /usr/local/Cellar/qt/6.3.2/share/qt/mkspecs/features/mac/sdk.mk
first: all
####### Build rules

kd_tree:  $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET)  $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: kd_tree.pro .qmake.cache /usr/local/share/qt/mkspecs/macx-clang/qmake.conf /usr/local/share/qt/mkspecs/features/spec_pre.prf \
		/usr/local/share/qt/mkspecs/features/device_config.prf \
		/usr/local/Cellar/qt/6.3.2/share/qt/mkspecs/common/unix.conf \
		/usr/local/Cellar/qt/6.3.2/share/qt/mkspecs/common/mac.conf \
		/usr/local/Cellar/qt/6.3.2/share/qt/mkspecs/common/macx.conf \
		/usr/local/Cellar/qt/6.3.2/share/qt/mkspecs/common/sanitize.conf \
		/usr/local/Cellar/qt/6.3.2/share/qt/mkspecs/common/gcc-base.conf \
		/usr/local/Cellar/qt/6.3.2/share/qt/mkspecs/common/gcc-base-mac.conf \
		/usr/local/Cellar/qt/6.3.2/share/qt/mkspecs/common/clang.conf \
		/usr/local/Cellar/qt/6.3.2/share/qt/mkspecs/common/clang-mac.conf \
		/usr/local/share/qt/mkspecs/qconfig.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_3danimation.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_3danimation_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_3dcore.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_3dcore_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_3dextras.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_3dextras_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_3dinput.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_3dinput_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_3dlogic.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_3dlogic_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_3dquick.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_3dquick_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_3dquickanimation.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_3dquickanimation_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_3dquickextras.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_3dquickextras_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_3dquickinput.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_3dquickinput_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_3dquickrender.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_3dquickrender_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_3dquickscene2d.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_3dquickscene2d_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_3drender.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_3drender_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_bluetooth.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_bluetooth_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_bodymovin_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_charts.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_charts_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_chartsqml.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_chartsqml_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_coap.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_coap_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_core.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_core5compat.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_core5compat_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_core_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_datavisualization.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_datavisualization_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_datavisualizationqml.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_datavisualizationqml_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_dbus.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_declarativeopcua.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_declarativeopcua_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_designer.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_designer_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_designercomponents_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_fb_support_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_gui.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_harfbuzz_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_help.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_help_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_hunspellinputmethod_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_jsonrpc_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_labsanimation.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_labsanimation_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_labsfolderlistmodel.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_labsfolderlistmodel_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_labsqmlmodels.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_labsqmlmodels_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_labssettings.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_labssettings_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_labssharedimage.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_labssharedimage_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_labswavefrontmesh.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_labswavefrontmesh_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_languageserver_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_linguist.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_linguist_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_mqtt.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_mqtt_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_multimedia.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_multimedia_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_multimediaquick_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_multimediawidgets.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_network.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_network_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_networkauth.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_networkauth_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_nfc.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_nfc_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_opcua.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_opcua_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_opengl.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_openglwidgets.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_openglwidgets_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_positioning.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_positioning_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_positioningquick.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_positioningquick_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_qml.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_qml_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_qmlcompiler_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_qmlcore.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_qmlcore_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_qmldebug_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_qmldom_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_qmlintegration.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_qmlintegration_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_qmllint_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_qmllocalstorage.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_qmllocalstorage_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_qmlmodels.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_qmlmodels_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_qmltest.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_qmltest_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_qmlworkerscript.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_qmlworkerscript_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_qmlxmllistmodel.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_qmlxmllistmodel_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_quick.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_quick3d.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_quick3d_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_quick3dassetimport.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_quick3dassetimport_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_quick3dassetutils.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_quick3dassetutils_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_quick3deffects.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_quick3deffects_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_quick3dglslparser_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_quick3dhelpers.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_quick3dhelpers_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_quick3diblbaker.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_quick3diblbaker_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_quick3dparticleeffects.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_quick3dparticleeffects_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_quick3dparticles.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_quick3dparticles_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_quick3druntimerender.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_quick3druntimerender_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_quick3dutils.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_quick3dutils_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_quick_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_quickcontrols2.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_quickcontrols2impl.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_quickcontrols2impl_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_quickcontrolstestutilsprivate_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_quickdialogs2.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_quickdialogs2_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_quickdialogs2quickimpl.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_quickdialogs2quickimpl_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_quickdialogs2utils.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_quickdialogs2utils_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_quicklayouts.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_quicklayouts_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_quickparticles_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_quickshapes_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_quicktemplates2.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_quicktestutilsprivate_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_quicktimeline.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_quicktimeline_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_quickwidgets.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_remoteobjects.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_remoteobjects_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_remoteobjectsqml.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_remoteobjectsqml_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_repparser.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_repparser_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_scxml.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_scxml_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_scxmlqml.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_scxmlqml_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_sensors.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_sensors_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_sensorsquick.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_sensorsquick_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_serialbus.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_serialbus_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_serialport.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_serialport_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_shadertools.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_shadertools_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_sql.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_statemachine.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_statemachine_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_statemachineqml.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_statemachineqml_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_svg.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_svg_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_svgwidgets.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_svgwidgets_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_testlib.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_tools_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_uiplugin.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_uitools.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_uitools_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_virtualkeyboard.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_virtualkeyboard_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_webchannel.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_webchannel_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_websockets.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_websockets_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_webview.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_webview_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_webviewquick.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_webviewquick_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_widgets.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_xml.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/local/share/qt/mkspecs/features/qt_functions.prf \
		/usr/local/share/qt/mkspecs/features/qt_config.prf \
		/usr/local/share/qt/mkspecs/macx-clang/qmake.conf \
		/usr/local/share/qt/mkspecs/features/spec_post.prf \
		.qmake.cache \
		.qmake.stash \
		/usr/local/share/qt/mkspecs/features/exclusive_builds.prf \
		/usr/local/share/qt/mkspecs/features/mac/sdk.prf \
		/usr/local/share/qt/mkspecs/features/toolchain.prf \
		/usr/local/share/qt/mkspecs/features/mac/toolchain.prf \
		/usr/local/share/qt/mkspecs/features/default_pre.prf \
		/usr/local/share/qt/mkspecs/features/mac/default_pre.prf \
		/usr/local/share/qt/mkspecs/features/resolve_config.prf \
		/usr/local/share/qt/mkspecs/features/default_post.prf \
		/usr/local/share/qt/mkspecs/features/mac/default_post.prf \
		/usr/local/share/qt/mkspecs/features/mac/objective_c.prf \
		/usr/local/share/qt/mkspecs/features/mac/mac.prf \
		/usr/local/share/qt/mkspecs/features/warn_on.prf \
		/usr/local/share/qt/mkspecs/features/qmake_use.prf \
		/usr/local/share/qt/mkspecs/features/file_copies.prf \
		/usr/local/share/qt/mkspecs/features/mac/rez.prf \
		/usr/local/share/qt/mkspecs/features/mac/asset_catalogs.prf \
		/usr/local/share/qt/mkspecs/features/testcase_targets.prf \
		/usr/local/share/qt/mkspecs/features/exceptions.prf \
		/usr/local/share/qt/mkspecs/features/yacc.prf \
		/usr/local/share/qt/mkspecs/features/lex.prf \
		kd_tree.pro
	$(QMAKE) -o Makefile kd_tree.pro
/usr/local/share/qt/mkspecs/features/spec_pre.prf:
/usr/local/share/qt/mkspecs/features/device_config.prf:
/usr/local/Cellar/qt/6.3.2/share/qt/mkspecs/common/unix.conf:
/usr/local/Cellar/qt/6.3.2/share/qt/mkspecs/common/mac.conf:
/usr/local/Cellar/qt/6.3.2/share/qt/mkspecs/common/macx.conf:
/usr/local/Cellar/qt/6.3.2/share/qt/mkspecs/common/sanitize.conf:
/usr/local/Cellar/qt/6.3.2/share/qt/mkspecs/common/gcc-base.conf:
/usr/local/Cellar/qt/6.3.2/share/qt/mkspecs/common/gcc-base-mac.conf:
/usr/local/Cellar/qt/6.3.2/share/qt/mkspecs/common/clang.conf:
/usr/local/Cellar/qt/6.3.2/share/qt/mkspecs/common/clang-mac.conf:
/usr/local/share/qt/mkspecs/qconfig.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_3danimation.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_3danimation_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_3dcore.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_3dcore_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_3dextras.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_3dextras_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_3dinput.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_3dinput_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_3dlogic.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_3dlogic_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_3dquick.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_3dquick_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_3dquickanimation.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_3dquickanimation_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_3dquickextras.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_3dquickextras_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_3dquickinput.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_3dquickinput_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_3dquickrender.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_3dquickrender_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_3dquickscene2d.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_3dquickscene2d_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_3drender.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_3drender_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_bluetooth.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_bluetooth_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_bodymovin_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_charts.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_charts_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_chartsqml.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_chartsqml_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_coap.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_coap_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_concurrent.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_concurrent_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_core.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_core5compat.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_core5compat_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_core_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_datavisualization.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_datavisualization_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_datavisualizationqml.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_datavisualizationqml_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_dbus.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_dbus_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_declarativeopcua.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_declarativeopcua_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_designer.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_designer_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_designercomponents_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_devicediscovery_support_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_fb_support_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_gui.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_gui_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_harfbuzz_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_help.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_help_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_hunspellinputmethod_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_jsonrpc_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_labsanimation.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_labsanimation_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_labsfolderlistmodel.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_labsfolderlistmodel_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_labsqmlmodels.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_labsqmlmodels_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_labssettings.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_labssettings_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_labssharedimage.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_labssharedimage_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_labswavefrontmesh.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_labswavefrontmesh_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_languageserver_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_linguist.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_linguist_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_mqtt.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_mqtt_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_multimedia.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_multimedia_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_multimediaquick_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_multimediawidgets.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_multimediawidgets_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_network.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_network_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_networkauth.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_networkauth_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_nfc.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_nfc_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_opcua.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_opcua_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_opengl.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_opengl_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_openglwidgets.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_openglwidgets_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_packetprotocol_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_positioning.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_positioning_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_positioningquick.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_positioningquick_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_printsupport.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_printsupport_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_qml.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_qml_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_qmlcompiler_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_qmlcore.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_qmlcore_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_qmldebug_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_qmldom_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_qmlintegration.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_qmlintegration_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_qmllint_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_qmllocalstorage.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_qmllocalstorage_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_qmlmodels.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_qmlmodels_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_qmltest.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_qmltest_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_qmlworkerscript.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_qmlworkerscript_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_qmlxmllistmodel.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_qmlxmllistmodel_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_quick.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_quick3d.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_quick3d_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_quick3dassetimport.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_quick3dassetimport_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_quick3dassetutils.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_quick3dassetutils_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_quick3deffects.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_quick3deffects_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_quick3dglslparser_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_quick3dhelpers.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_quick3dhelpers_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_quick3diblbaker.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_quick3diblbaker_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_quick3dparticleeffects.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_quick3dparticleeffects_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_quick3dparticles.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_quick3dparticles_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_quick3druntimerender.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_quick3druntimerender_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_quick3dutils.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_quick3dutils_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_quick_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_quickcontrols2.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_quickcontrols2_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_quickcontrols2impl.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_quickcontrols2impl_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_quickcontrolstestutilsprivate_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_quickdialogs2.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_quickdialogs2_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_quickdialogs2quickimpl.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_quickdialogs2quickimpl_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_quickdialogs2utils.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_quickdialogs2utils_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_quicklayouts.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_quicklayouts_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_quickparticles_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_quickshapes_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_quicktemplates2.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_quicktemplates2_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_quicktestutilsprivate_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_quicktimeline.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_quicktimeline_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_quickwidgets.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_quickwidgets_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_remoteobjects.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_remoteobjects_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_remoteobjectsqml.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_remoteobjectsqml_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_repparser.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_repparser_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_scxml.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_scxml_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_scxmlqml.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_scxmlqml_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_sensors.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_sensors_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_sensorsquick.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_sensorsquick_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_serialbus.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_serialbus_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_serialport.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_serialport_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_shadertools.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_shadertools_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_sql.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_sql_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_statemachine.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_statemachine_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_statemachineqml.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_statemachineqml_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_svg.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_svg_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_svgwidgets.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_svgwidgets_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_testlib.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_testlib_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_tools_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_uiplugin.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_uitools.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_uitools_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_virtualkeyboard.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_virtualkeyboard_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_webchannel.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_webchannel_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_websockets.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_websockets_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_webview.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_webview_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_webviewquick.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_webviewquick_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_widgets.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_widgets_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_xml.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_xml_private.pri:
/usr/local/share/qt/mkspecs/features/qt_functions.prf:
/usr/local/share/qt/mkspecs/features/qt_config.prf:
/usr/local/share/qt/mkspecs/macx-clang/qmake.conf:
/usr/local/share/qt/mkspecs/features/spec_post.prf:
.qmake.cache:
.qmake.stash:
/usr/local/share/qt/mkspecs/features/exclusive_builds.prf:
/usr/local/share/qt/mkspecs/features/mac/sdk.prf:
/usr/local/share/qt/mkspecs/features/toolchain.prf:
/usr/local/share/qt/mkspecs/features/mac/toolchain.prf:
/usr/local/share/qt/mkspecs/features/default_pre.prf:
/usr/local/share/qt/mkspecs/features/mac/default_pre.prf:
/usr/local/share/qt/mkspecs/features/resolve_config.prf:
/usr/local/share/qt/mkspecs/features/default_post.prf:
/usr/local/share/qt/mkspecs/features/mac/default_post.prf:
/usr/local/share/qt/mkspecs/features/mac/objective_c.prf:
/usr/local/share/qt/mkspecs/features/mac/mac.prf:
/usr/local/share/qt/mkspecs/features/warn_on.prf:
/usr/local/share/qt/mkspecs/features/qmake_use.prf:
/usr/local/share/qt/mkspecs/features/file_copies.prf:
/usr/local/share/qt/mkspecs/features/mac/rez.prf:
/usr/local/share/qt/mkspecs/features/mac/asset_catalogs.prf:
/usr/local/share/qt/mkspecs/features/testcase_targets.prf:
/usr/local/share/qt/mkspecs/features/exceptions.prf:
/usr/local/share/qt/mkspecs/features/yacc.prf:
/usr/local/share/qt/mkspecs/features/lex.prf:
kd_tree.pro:
qmake: FORCE
	@$(QMAKE) -o Makefile kd_tree.pro

qmake_all: FORCE


all: Makefile kd_tree

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) .qmake.stash
	-$(DEL_FILE) Makefile


####### Sub-libraries

xcodeproj:
	@$(QMAKE) -spec macx-xcode "$(EXPORT__PRO_FILE_)"

check: first

benchmark: first

compiler_rez_source_make_all:
compiler_rez_source_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: 

####### Compile

kd_tree.o: kd_tree.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o kd_tree.o kd_tree.cpp

test-harness.o: test-harness.cpp kd_tree.h \
		Point.h \
		BoundedPQueue.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o test-harness.o test-harness.cpp

####### Install

install:  FORCE

uninstall:  FORCE

FORCE:

